-- ============================================================
-- SEED DATA FOR LaptopHub (Normalized 3NF Schema)
-- ============================================================
-- NOTE: Passwords below are BCrypt hashes of "Test@123"
-- (generated by PasswordUtil.getHashPassword("Test@123"))
-- In a real app, passwords are NEVER stored as plaintext.
-- ============================================================

USE laptophub;

-- Clear existing data in correct order (child tables first)
DELETE FROM Payment;
DELETE FROM Review;
DELETE FROM OrderItem;
DELETE FROM `Order`;
DELETE FROM CartItem;
DELETE FROM Cart;
DELETE FROM LaptopCategory;
DELETE FROM Laptop;
DELETE FROM Category;
DELETE FROM Brand;
DELETE FROM User;

-- Reset auto-increment
ALTER TABLE User AUTO_INCREMENT = 1;
ALTER TABLE Brand AUTO_INCREMENT = 1;
ALTER TABLE Category AUTO_INCREMENT = 1;
ALTER TABLE Laptop AUTO_INCREMENT = 1;
ALTER TABLE Cart AUTO_INCREMENT = 1;
ALTER TABLE `Order` AUTO_INCREMENT = 1;
ALTER TABLE OrderItem AUTO_INCREMENT = 1;
ALTER TABLE Payment AUTO_INCREMENT = 1;
ALTER TABLE Review AUTO_INCREMENT = 1;

-- ========== Users ==========
-- Password for all users: "Test@123"
INSERT INTO User (username, email, password, phone, address, role, registration_date, last_login) VALUES
                                                                                                      ('admin', 'admin@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa', NULL, NULL, 'admin', CURDATE(), NULL),
                                                                                                      ('testuser', 'test@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa', '555-1234', '123 Main St', 'customer', CURDATE(), NULL),
                                                                                                      ('demouser', 'demo@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa', '555-5678', '456 Oak Ave', 'customer', CURDATE(), NULL);

-- ========== Brands ==========
INSERT INTO Brand (brand_name, brand_logo_url) VALUES
                                                   ('Dell', 'dell_logo.png'),
                                                   ('Lenovo', 'lenovo_logo.png'),
                                                   ('Apple', 'apple_logo.png'),
                                                   ('HP', 'hp_logo.png');

-- ========== Categories ==========
INSERT INTO Category (category_name) VALUES
                                         ('Gaming'),
                                         ('Business'),
                                         ('Ultrabook'),
                                         ('Student');

-- ========== Laptops ==========
INSERT INTO Laptop (brand_id, model, processor, ram, storage, price, stock_quantity, description, added_date) VALUES
                                                                                                                  (1, 'XPS 13', 'Intel i7-12700H', '16GB', '512GB SSD', 999.99, 10, 'A powerful laptop for professionals.', CURDATE()),
                                                                                                                  (1, 'Inspiron 15', 'Intel i5-1235U', '8GB', '256GB SSD', 499.99, 20, 'A budget-friendly laptop for students.', CURDATE()),
                                                                                                                  (2, 'Legion 5', 'AMD Ryzen 7 5800H', '32GB', '1TB SSD', 1499.99, 5, 'A gaming laptop with high-end specs.', CURDATE()),
                                                                                                                  (3, 'MacBook Air', 'Apple M2', '8GB', '256GB SSD', 999.00, 8, 'Lightweight and powerful ultrabook.', CURDATE()),
                                                                                                                  (4, 'Pavilion', 'Intel i7-1165G7', '16GB', '512GB SSD', 799.99, 12, 'Versatile laptop for home and office.', CURDATE());

-- Map Laptop IDs based on insertion order (Laptop IDs from 1 to 5)

-- ========== LaptopCategory (many-to-many) ==========
-- Laptop 1 (XPS 13) -> Ultrabook, Business
-- Laptop 2 (Inspiron 15) -> Student, Business
-- Laptop 3 (Legion 5) -> Gaming
-- Laptop 4 (MacBook Air) -> Ultrabook, Business
-- Laptop 5 (Pavilion) -> Business

INSERT INTO LaptopCategory (laptop_id, category_id) VALUES
                                                        (1, 3), (1, 2),   -- XPS 13: Ultrabook + Business
                                                        (2, 4), (2, 2),   -- Inspiron 15: Student + Business
                                                        (3, 1),           -- Legion 5: Gaming
                                                        (4, 3), (4, 2),   -- MacBook Air: Ultrabook + Business
                                                        (5, 2);           -- Pavilion: Business

-- ========== Carts ==========
-- Each customer gets a cart (user_id 2 and 3)
INSERT INTO Cart (user_id) VALUES (2), (3);

-- ========== Cart Items ==========
-- User testuser (cart_id=1) has 2 XPS 13 in cart
-- User demouser (cart_id=2) has 1 Legion 5 in cart
INSERT INTO CartItem (cart_id, laptop_id, quantity) VALUES
                                                        (1, 1, 2),
                                                        (2, 3, 1);

-- ========== Orders ==========
-- Order from testuser
INSERT INTO `Order` (user_id, order_date, total_amount, shipping_address, order_status) VALUES
                                                                                            (2, NOW(), 1999.98, '123 Main St', 'Delivered'),
                                                                                            (3, NOW(), 1499.99, '456 Oak Ave', 'Shipped');

-- ========== Order Items ==========
-- Order 1: 2 units of XPS 13 at 999.99 each
-- Order 2: 1 unit of Legion 5 at 1499.99
INSERT INTO OrderItem (order_id, laptop_id, quantity, unit_price) VALUES
                                                                      (1, 1, 2, 999.99),
                                                                      (2, 3, 1, 1499.99);

-- ========== Payments ==========
INSERT INTO Payment (order_id, payment_method, payment_status, transaction_id, payment_date) VALUES
                                                                                                 (1, 'Credit Card', 'Completed', 'TXN_TEST123', NOW()),
                                                                                                 (2, 'PayPal', 'Pending', 'TXN_TEST456', NOW());

-- ========== Reviews ==========
-- testuser reviews XPS 13
INSERT INTO Review (laptop_id, user_id, rating, comment, review_date) VALUES
                                                                          (1, 2, 5, 'Excellent laptop – fast and sleek!', CURDATE()),
                                                                          (3, 3, 4, 'Great for gaming, but battery drains fast.', CURDATE());

-- ============================================================
-- Optional: Verify data counts
-- ============================================================
SELECT 'Seed completed successfully.' AS Status;
SELECT COUNT(*) AS Users FROM User;
SELECT COUNT(*) AS Brands FROM Brand;
SELECT COUNT(*) AS Categories FROM Category;
SELECT COUNT(*) AS Laptops FROM Laptop;
SELECT COUNT(*) AS LaptopCategories FROM LaptopCategory;
SELECT COUNT(*) AS Carts FROM Cart;
SELECT COUNT(*) AS CartItems FROM CartItem;
SELECT COUNT(*) AS Orders FROM `Order`;
SELECT COUNT(*) AS OrderItems FROM OrderItem;
SELECT COUNT(*) AS Payments FROM Payment;
SELECT COUNT(*) AS Reviews FROM Review;